### ISSUE TITLE
No discoverable hosts

### ISSUE THREAD

**Issue by sigmaSd** [lemunozm/termchat#1]
Hi, this looks like an awesome project!

Regarding this issue, termchat doesn't detect the other instances (tested on different pc s over lan, same pc, same pc and a virtual box)(linux)
I'm not really sure how to debug udp_multicast locally, `ss -u` shows the connection but I'm not sure whats  the next step of debugging

**Comment by lemunozm** [comment]
Hi @sigmaSd, I'm glad you like it :)

The instances need to have different names in order to find themself. Could you confirm that your termchat instances are using different names?

By default, termchat use the OS username when running a new instance. Maybe you will need to specify a name, the argument `-u <name>` can be used for that.

Could you confirm if the issue happens with different instance names?
Thanks!

**Comment by sigmaSd** [comment]
Yes My 2 pc don't share the same name.

Also a question, if I run on the same pc 2 instances with 2 different user names, is it suppose to work in that case ?(Because if its the case it will easier up debugging)

**Comment by sigmaSd** [comment]
Ok some development

If I have an instance on pc1 and then run on pc2, pc1 will crash here https://github.com/lemunozm/termchat/blob/master/src/application.rs#L83

the problem is its getting ip addr "0.0.0.0:port" instead of "192.168.x.x"

**Comment by lemunozm** [comment]
Yes, if you run 2 instance with different names in the same pc should be
work.

These days I can not test it with several PCs, but I keep it in mind to
test the issue.

Which distribution of linux are you using?

**Comment by sigmaSd** [comment]
1-archlinux 1-solus os
so on the solus machine I can run multiple instance on the same host
on arch linux I can't

**Comment by sigmaSd** [comment]
Changing the address here https://github.com/lemunozm/termchat/blob/master/src/application.rs#L70 to the one in ifconfig makes it possible to use multiple instances on archlinux
But now something else going on when us it with this patch the other client on solus hangs

**Comment by sigmaSd** [comment]
It hang on `Networkmanger::connect_tcp`.
(btw I'll try to summarize my findings later, I'm updating the issue in case a problem is obvious to you)

**Comment by sigmaSd** [comment]
Ok Summary:
Turns out I had to stop ufw(linux firewall) even locally for it to works.

So current issues:
- I think connection being blocked by a firewall should be an error instead of a silent ignore (Or just adding this to the documentation if its not an easy task)
- Connecting to a remote machine fails here https://github.com/lemunozm/termchat/blob/master/src/application.rs#L83, source address should be converted by the sender from "0.0.0.0" to a lan one "192.168.x.x"
- (Might be a local issue) Changing the address to "192.168.x.x" makes the other pc hangs at  Networkmanager::connect_tcp (gdb)

**Comment by sigmaSd** [comment]
Actually for the third issue it works if arch starts before solus so it might be some local issue

**Comment by sigmaSd** [comment]
this diff fixes the main issue
```diff
diff --git a/src/network.rs b/src/network.rs
index 5912231..85a7f78 100644
--- a/src/network.rs
+++ b/src/network.rs
@@ -128,7 +128,9 @@ impl<'a> NetworkManager {
     pub fn listen_tcp<A: ToSocketAddrs>(&mut self, addr: A) -> io::Result<(usize, SocketAddr)> {
         let addr = addr.to_socket_addrs().unwrap().next().unwrap();
         Listener::new_tcp(addr).map(|listener| {
-            self.network_controller.lock().unwrap().add_listener(listener)
+            let addr = listener.local_addr();
+            let (n,_) = self.network_controller.lock().unwrap().add_listener(listener);
+            (n, addr)
         })
     }
```

**Comment by sigmaSd** [comment]
We can get local address like this, I'm not sure if there is a better way
```rust 
let socket = std::net::UdpSocket::bind("0.0.0.0:0").unwrap();

socket.connect("8.8.8.8:80").unwrap();
// or without internet
//socket.connect("192.168.1.1:8000").unwrap();

socket.local_addr().unwrap().ip()
```

**Comment by sigmaSd** [comment]
or even router address "192.168.1.1"

**Comment by sigmaSd** [comment]
Looks like this is the magic address `"10.255.255.255:1"` I tested it and it works even without internet 

taken from here https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib

**Comment by sigmaSd** [comment]
Here is a fix proposal 
```diff
diff --git a/src/application.rs b/src/application.rs
index d8f83cd..4f85bdb 100644
--- a/src/application.rs
+++ b/src/application.rs
@@ -67,7 +67,9 @@ impl Application {
         let mut state = ApplicationState::new();
         ui::draw(&mut self.terminal, &state);
 
-        let (_, server_addr) = self.network.listen_tcp("0.0.0.0:0").unwrap();
+        let local_addr = get_local_addr();
+        let (_, server_addr) = self.network.listen_tcp(local_addr).unwrap();
+        
         self.network.listen_udp_multicast(self.discovery_addr).unwrap();
 
         let discovery_endpoint = self.network.connect_udp(self.discovery_addr).unwrap();
@@ -166,3 +168,9 @@ impl Drop for Application {
     }
 }
 
+fn get_local_addr() -> String {
+       //https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib
+       let socket = std::net::UdpSocket::bind("0.0.0.0:0").unwrap();
+       socket.connect("10.255.255.255:1").unwrap();
+       format!("{}:0",socket.local_addr().unwrap().ip().to_string())
+}
```

**Comment by lemunozm** [comment]
Hi @sigmaSd, I proceed to answer some things:
1. Regarding the firewall issue, the program has no chance of detecting it, since this is due to the topology of the network. Also, if the router has disabled the UDP multicast option, the program will not work, but there is no way to know it from its point of view (as far as I know). I like your recommendation to put it in the documentation :)
2. The IP address placed in the `NetworkManager::listen_tcp()` corresponds to the interface from the socket will be listened (internally it makes a poxis `bind()`). That is: if you put the `127.0.0.1` address, only data from localhost will be listened; if you put your local address, only data from your LAN will be listened; and if you put `0.0.0.0` data from "anywhere" will be listened (that is what we want). I do not know exactly why you achieve communication with the patch you suggest and why not with the `0.0.0.0`. I will investigate.

**Comment by sigmaSd** [comment]
Its ok to listen on 0.0.0.0 the problem is not what ip to listen on, but what ip you send on your messages.

Example:
Pc1 listen on 0.0.0.0 when he send a msg to another pc that hes alive it will a contain pc1_addr=0.0.0.0 which is incorrect for pc2.

Also By saying anywhere, do you mean termchat works over internet too? If that the case also the same problem happens, the message needs to contain the wan public ip address

**Comment by sigmaSd** [comment]
So something like this:
```diff
diff --git a/src/application.rs b/src/application.rs
index d8f83cd..db9b74c 100644
--- a/src/application.rs
+++ b/src/application.rs
@@ -68,10 +68,12 @@ impl Application {
         ui::draw(&mut self.terminal, &state);
 
         let (_, server_addr) = self.network.listen_tcp("0.0.0.0:0").unwrap();
+        let local_addr = get_local_addr(server_addr.port());
+        
         self.network.listen_udp_multicast(self.discovery_addr).unwrap();
 
         let discovery_endpoint = self.network.connect_udp(self.discovery_addr).unwrap();
-        self.network.send(discovery_endpoint, NetMessage::HelloLan(self.user_name.clone(), server_addr)).unwrap();
+        self.network.send(discovery_endpoint, NetMessage::HelloLan(self.user_name.clone(), local_addr)).unwrap();
 
         loop {
             match self.event_queue.receive() {
@@ -166,3 +168,9 @@ impl Drop for Application {
     }
 }
 
+fn get_local_addr(server_port: u16) -> std::net::SocketAddr {
+       //https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib
+       let socket = std::net::UdpSocket::bind("0.0.0.0:0").unwrap();
+       socket.connect("10.255.255.255:1").unwrap();
+       format!("{}:{}",socket.local_addr().unwrap().ip(), server_port).parse().unwrap()
+}
```

**Comment by lemunozm** [comment]
Yes, it's true that to send the server_addr in the HelloLan message is wrong. Good view :)

Regarding your propose, It will work but only if the interface from you connect to 10.255.255.255 is the same as the interface from other instance has found you. If your PC has several interfaces, it could be not work. 

I have another propose to fix it. Instead of sending the server_addr entirely, send only the server port. And from the other instance get the remote address from the endpoint.

If you want, you can make a Pull Request with this change :)

**Comment by sigmaSd** [comment]
Cool that works I tried it.
Can you before I make this PR run cargo fmt (and optionally fix clippy errors) on the code base. (same for message-io)
Most editors now have auto-format on save by default so its making contributing a bit troublesome.

**Comment by lemunozm** [comment]
Sorry, I have not an accesible computer for the next 2 weeks :S

I usually not use the rust fmt because in some parts a "custom" format is more readable (in some tricky parts). Anyway, I will analyze it. Last time I tested the rust fmt was some years ago and has few config options. I think that the config file has been improved with more options and the result will be more acuracy.

**Comment by sigmaSd** [comment]
I think its by now a well known standard on the rust ecosystem. Also the config file let you fix the parts you don't like while still making *contributing* very accessible.

Anyhow maybe check it out again when you have time to analyse it. (+ computer ofc xD)
